---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: projects
  label: projects
  create: documents
  match: "**/*"
- type: document
  path: README.md
  label: Homepage
- type: directory
  path: posts
  label: blog posts
  create: all
  match: "**/*"
upload_dir: ".vuepress/public/img"
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  instant_preview_command: npm run develop
